"""SQLite-Persistenz für StockWatch."""

from .connection import DEFAULT_DATABASE_PATH, create_database, create_session_factory
from .catalog_import import CSV_FIELDS, ImportSummary, import_securities_csv
from .api_usage import ApiLimits, ApiUsageService, ApiUsageStatus
from .models import (
    AnalysisSnapshot,
    AnalystRecommendation,
    ApiUsage,
    AiUsage,
    AiNewsAssessment,
    Base,
    CompanyData,
    EarningsResult,
    NewsItem,
    Position,
    PRICE_TYPES,
    ProviderCapability,
    ProviderCache,
    SecurityCatalog,
    SchedulerRun,
    SchedulerSetting,
    ScannerCandidate,
    ScannerCandidateTechnical,
    ScannerAiAssessment,
    ScannerAiNewsAssessment,
    OpportunityWatchlist,
    OpportunityCandidateSummary,
    OpportunityWatchObservation,
    OpportunitySearchRun,
    OpportunityNewsEvent,
    ManualActionRun,
    ScannerProviderCapability,
    ScannerRun,
    ScannerSecurityState,
    ScannerTechnicalRun,
    Stock,
    StockAiAnalysis,
    StockProviderSetting,
    StockProviderSymbol,
    UpdateSchedule,
)
from .repository import StockWatchRepository
from .search import SearchService
from .service import (
    DashboardData,
    PositionMetrics,
    StockWatchService,
    calculate_position_metrics,
)

__all__ = [
    "AnalysisSnapshot",
    "AnalystRecommendation",
    "ApiLimits",
    "ApiUsage",
    "AiUsage",
    "AiNewsAssessment",
    "ApiUsageService",
    "ApiUsageStatus",
    "Base",
    "CompanyData",
    "EarningsResult",
    "NewsItem",
    "CSV_FIELDS",
    "DEFAULT_DATABASE_PATH",
    "DashboardData",
    "Position",
    "PRICE_TYPES",
    "PositionMetrics",
    "ProviderCapability",
    "ProviderCache",
    "ImportSummary",
    "SearchService",
    "SecurityCatalog",
    "SchedulerRun",
    "SchedulerSetting",
    "ScannerCandidate",
    "ScannerCandidateTechnical",
    "ScannerAiAssessment",
    "ScannerAiNewsAssessment",
    "OpportunityWatchlist",
    "OpportunityCandidateSummary",
    "OpportunityWatchObservation",
    "OpportunitySearchRun",
    "OpportunityNewsEvent",
    "ManualActionRun",
    "ScannerProviderCapability",
    "ScannerRun",
    "ScannerSecurityState",
    "ScannerTechnicalRun",
    "Stock",
    "StockAiAnalysis",
    "StockProviderSetting",
    "StockProviderSymbol",
    "UpdateSchedule",
    "StockWatchRepository",
    "StockWatchService",
    "create_database",
    "create_session_factory",
    "calculate_position_metrics",
    "import_securities_csv",
]
